restart_file: .na
start_datetime: 2021-10-25 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-10-26 00:00:00
forecast_horizon: 5
sim_name: test_run_2
forecast_site: fcre
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
