restart_file: .na
start_datetime: '2018-07-20'
end_datetime: .na
forecast_start_datetime: '2018-07-30'
forecast_horizon: 0.0
sim_name: test_run
forecast_output_directory: .na
forecast_configuration_directory: .na
execute_directory: .na
